In [1]:
import os
print(os.getcwd())
os.chdir('/home/bren901/coding/MH-GRAG')
print(os.getcwd())

/home/bren901/coding/MH-GRAG/tests
/home/bren901/coding/MH-GRAG

In [2]:
from src.utils.embedding_utils import load_df_from_csv_with_embedding
from src.utils.config import OUTPUT_PATH

final_entities=load_df_from_csv_with_embedding(f"/home/bren901/coding/MH-GRAG/export/entities_yntcsxiw.csv",['entity_embedding'])
final_entities

,entity_name,entity_type,description,entity_id,corpus_id,entity_embedding
0,AMAZON,ORGANIZATION,Amazon is a retail giant known for its extensi...,0,0,"[0.025474460795521736, -0.019272109493613243, ..."
1,CYBER MONDAY,EVENT,Cyber Monday is a significant shopping event t...,1,0,"[0.008677905425429344, -0.012837450951337814, ..."
2,BLACK FRIDAY,EVENT,Black Friday is a shopping holiday that takes ...,2,0,"[0.016857707872986794, -0.01078620832413435, -..."
3,"NOVEMBER 27, 2023",TIME,"November 27, 2023, is the date when Cyber Mond...",3,0,"[0.009768207557499409, -0.01335572637617588, -..."
4,AMAZON,ORGANIZATION,Amazon is a multinational technology company k...,4,1,"[0.029136504977941513, -0.007207231130450964, ..."
...,...,...,...,...,...,...
39353,ISRAEL-HAMAS WAR,EVENT,"A conflict involving Israel and Hamas, which h...",39353,4476,"[0.04042772203683853, -0.0035180281847715378, ..."
39354,EEA,LOCATION,The European Economic Area includes the Europe...,39354,4476,"[0.02691667526960373, -0.003410726087167859, -..."
39355,SWITZERLAND,LOCATION,A country in Europe that is part of the Europe...,39355,4476,"[0.015187944285571575, -0.011422696523368359, ..."
39356,DIGITAL SERVICES ACT,CONCEPT,The Digital Services Act is a regulation estab...,39356,4476,"[-0.010030446574091911, -0.01822492480278015, ..."
39357,DIGITAL MARKETS ACT,CONCEPT,The Digital Markets Act is a regulation by the...,39357,4476,"[-0.0020081689581274986, -0.01604270190000534,..."

In [3]:
final_relationships=load_df_from_csv_with_embedding(f"/home/bren901/coding/MH-GRAG/export/relationships_douqtaig.csv",['relationship_embedding'])
final_relationships

,source_entity,target_entity,relationship_description,relationship_strength,source_entity_id,target_entity_id,corpus_id,relationship_embedding
0,AMAZON,CYBER MONDAY,Amazon is hosting numerous deals during Cyber ...,9,0,1,0,"[0.02443057671189308, -0.03799114748835564, -0..."
1,AMAZON,BLACK FRIDAY,Amazon began its Black Friday sale a week ahea...,8,0,2,0,"[0.054795797914266586, -0.031081540510058403, ..."
2,CYBER MONDAY,BLACK FRIDAY,"Cyber Monday follows Black Friday, with many d...",7,1,2,0,"[0.009650849737226963, -0.029358115047216415, ..."
3,"NOVEMBER 27, 2023",CYBER MONDAY,"November 27, 2023, is the date that marks the ...",10,3,1,0,"[0.007443748414516449, -0.01130700297653675, -..."
4,AMAZON,ECHO SHOW,"Amazon produces the Echo Show, integrating it ...",8,4,5,1,"[0.045543570071458817, -0.009272989816963673, ..."
...,...,...,...,...,...,...,...,...
29203,META,ISRAEL-HAMAS WAR,Meta's approach to content regulation is being...,6,39351,39353,4476,"[0.04234350472688675, -0.02529730089008808, -0..."
29204,META,DIGITAL SERVICES ACT,Meta is designated as a gatekeeper under the D...,8,39351,39356,4476,"[0.034957364201545715, -0.028356697410345078, ..."
29205,META,DIGITAL MARKETS ACT,Meta is also impacted by the Digital Markets A...,8,39351,39357,4476,"[0.010328758507966995, -0.016240786761045456, ..."
29206,EEA,META,"Meta serves users across the EEA, impacting it...",7,39354,39351,4476,"[0.034811727702617645, -0.027029171586036682, ..."
29207,SWITZERLAND,META,"Meta's operations extend to Switzerland, which...",6,39355,39351,4476,"[0.02793646603822708, -0.030657349154353142, -..."

In [4]:
# 筛选 final_entities 中 corpus_id < 2000 的数据
filtered_final_entities = final_entities[final_entities['corpus_id'] < 2000]

# 筛选 final_relationships 中 source_entity_id 和 target_entity_id 对应的 corpus_id 都 < 2000 的数据
filtered_final_relationships = final_relationships[
    (final_relationships['source_entity_id'].isin(filtered_final_entities['entity_id'])) &
    (final_relationships['target_entity_id'].isin(filtered_final_entities['entity_id']))
]

filtered_final_entities

,entity_name,entity_type,description,entity_id,corpus_id,entity_embedding
0,AMAZON,ORGANIZATION,Amazon is a retail giant known for its extensi...,0,0,"[0.025474460795521736, -0.019272109493613243, ..."
1,CYBER MONDAY,EVENT,Cyber Monday is a significant shopping event t...,1,0,"[0.008677905425429344, -0.012837450951337814, ..."
2,BLACK FRIDAY,EVENT,Black Friday is a shopping holiday that takes ...,2,0,"[0.016857707872986794, -0.01078620832413435, -..."
3,"NOVEMBER 27, 2023",TIME,"November 27, 2023, is the date when Cyber Mond...",3,0,"[0.009768207557499409, -0.01335572637617588, -..."
4,AMAZON,ORGANIZATION,Amazon is a multinational technology company k...,4,1,"[0.029136504977941513, -0.007207231130450964, ..."
...,...,...,...,...,...,...
18083,PAUL POGBA,PERSON,Paul Pogba is a former football player for Uni...,18083,1999,"[0.04045560583472252, -0.0013302824227139354, ..."
18084,BRUNO FERNANDES,PERSON,Bruno Fernandes is a football player with lead...,18084,1999,"[0.029299458488821983, 0.002235568594187498, -..."
18085,HARRY MAGUIRE,PERSON,Harry Maguire is a football player known for h...,18085,1999,"[0.0343484953045845, -0.007848457433283329, -0..."
18086,CHELSEA,ORGANIZATION,Chelsea is a football club that competes with ...,18086,1999,"[0.013079955242574215, -0.0021568776573985815,..."
18087,UNITED,ORGANIZATION,United is a football club that has players lik...,18087,1999,"[0.039028365164995193, 0.0027184761129319668, ..."

In [5]:
filtered_final_relationships

,source_entity,target_entity,relationship_description,relationship_strength,source_entity_id,target_entity_id,corpus_id,relationship_embedding
0,AMAZON,CYBER MONDAY,Amazon is hosting numerous deals during Cyber ...,9,0,1,0,"[0.02443057671189308, -0.03799114748835564, -0..."
1,AMAZON,BLACK FRIDAY,Amazon began its Black Friday sale a week ahea...,8,0,2,0,"[0.054795797914266586, -0.031081540510058403, ..."
2,CYBER MONDAY,BLACK FRIDAY,"Cyber Monday follows Black Friday, with many d...",7,1,2,0,"[0.009650849737226963, -0.029358115047216415, ..."
3,"NOVEMBER 27, 2023",CYBER MONDAY,"November 27, 2023, is the date that marks the ...",10,3,1,0,"[0.007443748414516449, -0.01130700297653675, -..."
4,AMAZON,ECHO SHOW,"Amazon produces the Echo Show, integrating it ...",8,4,5,1,"[0.045543570071458817, -0.009272989816963673, ..."
...,...,...,...,...,...,...,...,...
13490,MANCHESTER UNITED,SATURDAY AFTERNOON,Saturday afternoon is when Manchester United i...,5,18073,18081,1998,"[0.06369853019714355, 0.0025729986373335123, -..."
13491,SCOTT MCTOMINAY,PAUL POGBA,McTominay is currently performing the role tha...,8,18082,18083,1999,"[0.050501130521297455, 0.005157089792191982, -..."
13492,SCOTT MCTOMINAY,BRUNO FERNANDES,Scott McTominay's performance is noted alongsi...,6,18082,18084,1999,"[0.046916376799345016, 0.013256392441689968, -..."
13493,SCOTT MCTOMINAY,HARRY MAGUIRE,Scott McTominay's role is highlighted in conju...,6,18082,18085,1999,"[0.06499527394771576, 0.009948339313268661, -0..."
13494,UNITED,CHELSEA,United and Chelsea are rival football clubs co...,9,18087,18086,1999,"[0.011529958806931973, 0.0008717533200979233, ..."

In [6]:
from src.gnn_clustering.data_loader import load_custom_data
from src.gnn_clustering.utils import get_device, get_dense_adj, communities_to_labels
from src.gnn_clustering.multihead_clustering import get_initial_leiden_results, get_clustering_results, convert_to_igraph
from src.utils.graph_utils import create_graph_from_df, generate_knn_graph_from_embeddings, combine_graphs_separately
from src.gnn_clustering.model import get_multi_head_model
from src.gnn_clustering.train import train_model_multi_head
from src.gnn_clustering.evaluate import get_embeddings_list
import torch

# 设置设备
device = get_device()

# 数据加载
data = load_custom_data(filtered_final_entities, filtered_final_relationships)
data = data.to(device)

# 训练模型
num_heads=3
multi_head_model = get_multi_head_model(data=data, device=device, num_heads=num_heads)
optimizer = torch.optim.Adam(multi_head_model.parameters(), lr=0.01)
adj = get_dense_adj(data.edge_index, device=device)

trained_model = train_model_multi_head(multi_head_model, data, adj, optimizer, num_heads)
embeddings_list_after_training = get_embeddings_list(trained_model, data, device)

graph_data, entity_id_to_index = create_graph_from_df(filtered_final_entities, filtered_final_relationships)
knn_graphs = []
for embedding in embeddings_list_after_training:
    knn_graph = generate_knn_graph_from_embeddings(embedding, k=2, fixed_weight=1.0)
    knn_graphs.append(knn_graph)

combined_graphs = combine_graphs_separately(graph_data, knn_graphs)

source_nodes = torch.tensor(filtered_final_relationships['source_entity_id'], dtype=torch.long)
target_nodes = torch.tensor(filtered_final_relationships['target_entity_id'], dtype=torch.long)

original_edge_index = torch.stack([source_nodes, target_nodes], dim=0)
original_graph = convert_to_igraph(original_edge_index)


# 执行测试
merge_leiden_results = get_initial_leiden_results(data=data, device=device)
multi_head_leiden_results = get_clustering_results(combined_graphs)

merge_communities_leiden = merge_leiden_results[0][0]
cluster_labels_merge = communities_to_labels(merge_communities_leiden, data.num_nodes)
filtered_final_entities['cluster_original'] = cluster_labels_merge

# 将多头聚类结果添加到DataFrame
for head_index, clustering_result in enumerate(multi_head_leiden_results):
    cluster_labels_multihead = communities_to_labels(clustering_result, data.num_nodes)
    filtered_final_entities[f'cluster_head_{head_index}'] = cluster_labels_multihead

# 打印结果确认
filtered_final_entities

/home/bren901/coding/bren_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Epoch 1, Loss: 674187.8750
Epoch 20, Loss: 247312.4375
Epoch 40, Loss: 117016.7578
Epoch 60, Loss: 108504.7500
Epoch 80, Loss: 106370.8906
Epoch 100, Loss: 103604.4531
Epoch 120, Loss: 91738.0234
Epoch 140, Loss: 2643.8604
Epoch 160, Loss: 1451.3024
Epoch 180, Loss: 424.4371
Epoch 200, Loss: 201.2845

/home/bren901/coding/MH-GRAG/src/utils/graph_utils.py:11: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at ../torch/csrc/utils/tensor_new.cpp:278.)
  edge_index = torch.tensor([source_indices, target_indices], dtype=torch.long)

Head 0: Combined edge index shape: torch.Size([2, 31570])
Head 0: Combined edge weights shape: torch.Size([31570])
Head 1: Combined edge index shape: torch.Size([2, 31570])
Head 1: Combined edge weights shape: torch.Size([31570])
Head 2: Combined edge index shape: torch.Size([2, 31570])
Head 2: Combined edge weights shape: torch.Size([31570])

/tmp/ipykernel_2149687/1977785721.py:47: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities['cluster_original'] = cluster_labels_merge
/tmp/ipykernel_2149687/1977785721.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities[f'cluster_head_{head_index}'] = cluster_labels_multihead
/tmp/ipykernel_2149687/1977785721.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities[f'cluster_head_{head_index}'] = cluster_labels_multihead
/tmp/ipykernel_2149687/1977785721.py:52: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities[f'cluster_head_{head_index}'] = cluster_labels_multihead

,entity_name,entity_type,description,entity_id,corpus_id,entity_embedding,cluster_original,cluster_head_0,cluster_head_1,cluster_head_2
0,AMAZON,ORGANIZATION,Amazon is a retail giant known for its extensi...,0,0,"[0.025474460795521736, -0.019272109493613243, ...",1639,11,55,7
1,CYBER MONDAY,EVENT,Cyber Monday is a significant shopping event t...,1,0,"[0.008677905425429344, -0.012837450951337814, ...",1639,11,55,7
2,BLACK FRIDAY,EVENT,Black Friday is a shopping holiday that takes ...,2,0,"[0.016857707872986794, -0.01078620832413435, -...",1639,11,55,7
3,"NOVEMBER 27, 2023",TIME,"November 27, 2023, is the date when Cyber Mond...",3,0,"[0.009768207557499409, -0.01335572637617588, -...",1639,11,2,10
4,AMAZON,ORGANIZATION,Amazon is a multinational technology company k...,4,1,"[0.029136504977941513, -0.007207231130450964, ...",317,16,50,24
...,...,...,...,...,...,...,...,...,...,...
18083,PAUL POGBA,PERSON,Paul Pogba is a former football player for Uni...,18083,1999,"[0.04045560583472252, -0.0013302824227139354, ...",1893,25,35,21
18084,BRUNO FERNANDES,PERSON,Bruno Fernandes is a football player with lead...,18084,1999,"[0.029299458488821983, 0.002235568594187498, -...",1893,7,35,21
18085,HARRY MAGUIRE,PERSON,Harry Maguire is a football player known for h...,18085,1999,"[0.0343484953045845, -0.007848457433283329, -0...",1893,25,35,21
18086,CHELSEA,ORGANIZATION,Chelsea is a football club that competes with ...,18086,1999,"[0.013079955242574215, -0.0021568776573985815,...",3254,8,30,808
18087,UNITED,ORGANIZATION,United is a football club that has players lik...,18087,1999,"[0.039028365164995193, 0.0027184761129319668, ...",3254,8,30,808

In [7]:
filtered_final_entities[filtered_final_entities["cluster_head_1"]==40]

,entity_name,entity_type,description,entity_id,corpus_id,entity_embedding,cluster_original,cluster_head_0,cluster_head_1,cluster_head_2
323,SCOTER'S COFFEE FRISCO BOWL,EVENT,The Scooter's Coffee Frisco Bowl is a postseas...,323,34,"[0.022065211087465286, -0.01155097596347332, -...",3297,7,40,28
1419,MAMMOTH,ORGANIZATION,Mammoth is a startup that creates a third-part...,1419,162,"[0.021822046488523483, -0.012662691995501518, ...",1685,2,40,33
1525,OPENAI,ORGANIZATION,OpenAI is an artificial intelligence research ...,1525,174,"[0.028959542512893677, -0.033238157629966736, ...",300,2,40,10
1526,ILA SUTSKEVER,PERSON,Ilya Sutskever is a co-founder and chief scien...,1526,174,"[-0.004398925695568323, -0.011558940634131432,...",300,2,40,10
1529,SILICON VALLEY,LOCATION,Silicon Valley is a region in California known...,1529,174,"[0.0156781617552042, -0.005470279138535261, -0...",300,3,40,10
...,...,...,...,...,...,...,...,...,...,...
17023,VICTOR ORTIZ,PERSON,Victor Ortiz is a professional boxer known for...,17023,1875,"[0.014207188971340656, -0.016986055299639702, ...",1881,23,40,20
17024,LARRY MERCHANT,PERSON,Larry Merchant is a veteran boxing commentator...,17024,1875,"[0.021948231384158134, -0.006442426238209009, ...",1881,22,40,20
17025,CONOR MCGREGOR,PERSON,Conor McGregor is a professional mixed martial...,17025,1875,"[0.025447841733694077, -0.018859753385186195, ...",1881,22,40,20
17310,ROLLERCOASTER,CONCEPT,A metaphor describing the emotional ups and do...,17310,1907,"[0.01228278037160635, -0.017341844737529755, -...",26,8,40,5
17622,MONDAY,TIME,Monday refers to the day when Sundar Pichai te...,17622,1951,"[0.0009640629286877811, -0.027700532227754593,...",127,4,40,8

In [9]:
filtered_final_entities[['entity_name', 'entity_type', 'description', 'entity_id', 'corpus_id', 'cluster_original', 'cluster_head_0',
       'cluster_head_1', 'cluster_head_2']].to_csv("export/entities_with_cluster_1020.csv",index=False)