In [2]:
import os
print(os.getcwd())
os.chdir('/home/bren901/coding/MH-GRAG')
print(os.getcwd())

In [2]:
from src.utils.embedding_utils import load_df_from_csv_with_embedding
from src.utils.config import OUTPUT_PATH

final_entities=load_df_from_csv_with_embedding(f"/home/bren901/coding/MH-GRAG/export/entities_yntcsxiw.csv",['entity_embedding'])
final_entities

,entity_name,entity_type,description,entity_id,corpus_id,entity_embedding
0,AMAZON,ORGANIZATION,Amazon is a retail giant known for its extensi...,0,0,"[0.025474460795521736, -0.019272109493613243, ..."
1,CYBER MONDAY,EVENT,Cyber Monday is a significant shopping event t...,1,0,"[0.008677905425429344, -0.012837450951337814, ..."
2,BLACK FRIDAY,EVENT,Black Friday is a shopping holiday that takes ...,2,0,"[0.016857707872986794, -0.01078620832413435, -..."
3,"NOVEMBER 27, 2023",TIME,"November 27, 2023, is the date when Cyber Mond...",3,0,"[0.009768207557499409, -0.01335572637617588, -..."
4,AMAZON,ORGANIZATION,Amazon is a multinational technology company k...,4,1,"[0.029136504977941513, -0.007207231130450964, ..."
...,...,...,...,...,...,...
39353,ISRAEL-HAMAS WAR,EVENT,"A conflict involving Israel and Hamas, which h...",39353,4476,"[0.04042772203683853, -0.0035180281847715378, ..."
39354,EEA,LOCATION,The European Economic Area includes the Europe...,39354,4476,"[0.02691667526960373, -0.003410726087167859, -..."
39355,SWITZERLAND,LOCATION,A country in Europe that is part of the Europe...,39355,4476,"[0.015187944285571575, -0.011422696523368359, ..."
39356,DIGITAL SERVICES ACT,CONCEPT,The Digital Services Act is a regulation estab...,39356,4476,"[-0.010030446574091911, -0.01822492480278015, ..."
39357,DIGITAL MARKETS ACT,CONCEPT,The Digital Markets Act is a regulation by the...,39357,4476,"[-0.0020081689581274986, -0.01604270190000534,..."

In [3]:
final_relationships=load_df_from_csv_with_embedding(f"/home/bren901/coding/MH-GRAG/export/relationships_douqtaig.csv",['relationship_embedding'])
final_relationships

,source_entity,target_entity,relationship_description,relationship_strength,source_entity_id,target_entity_id,corpus_id,relationship_embedding
0,AMAZON,CYBER MONDAY,Amazon is hosting numerous deals during Cyber ...,9,0,1,0,"[0.02443057671189308, -0.03799114748835564, -0..."
1,AMAZON,BLACK FRIDAY,Amazon began its Black Friday sale a week ahea...,8,0,2,0,"[0.054795797914266586, -0.031081540510058403, ..."
2,CYBER MONDAY,BLACK FRIDAY,"Cyber Monday follows Black Friday, with many d...",7,1,2,0,"[0.009650849737226963, -0.029358115047216415, ..."
3,"NOVEMBER 27, 2023",CYBER MONDAY,"November 27, 2023, is the date that marks the ...",10,3,1,0,"[0.007443748414516449, -0.01130700297653675, -..."
4,AMAZON,ECHO SHOW,"Amazon produces the Echo Show, integrating it ...",8,4,5,1,"[0.045543570071458817, -0.009272989816963673, ..."
...,...,...,...,...,...,...,...,...
29203,META,ISRAEL-HAMAS WAR,Meta's approach to content regulation is being...,6,39351,39353,4476,"[0.04234350472688675, -0.02529730089008808, -0..."
29204,META,DIGITAL SERVICES ACT,Meta is designated as a gatekeeper under the D...,8,39351,39356,4476,"[0.034957364201545715, -0.028356697410345078, ..."
29205,META,DIGITAL MARKETS ACT,Meta is also impacted by the Digital Markets A...,8,39351,39357,4476,"[0.010328758507966995, -0.016240786761045456, ..."
29206,EEA,META,"Meta serves users across the EEA, impacting it...",7,39354,39351,4476,"[0.034811727702617645, -0.027029171586036682, ..."
29207,SWITZERLAND,META,"Meta's operations extend to Switzerland, which...",6,39355,39351,4476,"[0.02793646603822708, -0.030657349154353142, -..."

In [4]:
# from sklearn.metrics.pairwise import cosine_similarity
# import numpy as np
# import pandas as pd
# from sentence_transformers import SentenceTransformer
# import numpy as np

# # 假设你使用 Sentence-BERT 作为嵌入模型
# model = SentenceTransformer('intfloat/multilingual-e5-large')

# # 将问题转换为嵌入向量
# def get_query_embedding(query):
#     query_embedding = model.encode(query)
#     return query_embedding

# # 计算查询嵌入和实体嵌入之间的余弦相似度
# def find_k_nearest_entities(query_embedding, final_entities, k=3):
#     # 过滤掉嵌入为空的情况
#     valid_entities = final_entities.dropna(subset=['entity_embedding'])
#     # 确保所有嵌入向量的维度一致
#     entity_embeddings = np.array([emb for emb in valid_entities['entity_embedding'].values if len(emb) == len(query_embedding)])
#     similarities = cosine_similarity([query_embedding], entity_embeddings)[0]
#     valid_entities = valid_entities.loc[valid_entities['entity_embedding'].apply(lambda x: len(x) == len(query_embedding))]
#     valid_entities['similarity'] = similarities
#     nearest_entities = valid_entities.sort_values(by='similarity', ascending=False).head(k)
#     return nearest_entities

# # 获取查询嵌入
# query = "what is Crimson Tide?"
# query_embedding = get_query_embedding(query)

# # 查询最相近的 k 个实体
# k = 3
# nearest_entities = find_k_nearest_entities(query_embedding, final_entities, k)
# nearest_entities[['entity_name','description', 'similarity']]

# 尝试进行RAG

In [5]:
# 筛选 final_entities 中 corpus_id < 2000 的数据
filtered_final_entities = final_entities[final_entities['corpus_id'] < 2000]

# 筛选 final_relationships 中 source_entity_id 和 target_entity_id 对应的 corpus_id 都 < 2000 的数据
filtered_final_relationships = final_relationships[
    (final_relationships['source_entity_id'].isin(filtered_final_entities['entity_id'])) &
    (final_relationships['target_entity_id'].isin(filtered_final_entities['entity_id']))
]

filtered_final_relationships

,source_entity,target_entity,relationship_description,relationship_strength,source_entity_id,target_entity_id,corpus_id,relationship_embedding
0,AMAZON,CYBER MONDAY,Amazon is hosting numerous deals during Cyber ...,9,0,1,0,"[0.02443057671189308, -0.03799114748835564, -0..."
1,AMAZON,BLACK FRIDAY,Amazon began its Black Friday sale a week ahea...,8,0,2,0,"[0.054795797914266586, -0.031081540510058403, ..."
2,CYBER MONDAY,BLACK FRIDAY,"Cyber Monday follows Black Friday, with many d...",7,1,2,0,"[0.009650849737226963, -0.029358115047216415, ..."
3,"NOVEMBER 27, 2023",CYBER MONDAY,"November 27, 2023, is the date that marks the ...",10,3,1,0,"[0.007443748414516449, -0.01130700297653675, -..."
4,AMAZON,ECHO SHOW,"Amazon produces the Echo Show, integrating it ...",8,4,5,1,"[0.045543570071458817, -0.009272989816963673, ..."
...,...,...,...,...,...,...,...,...
13490,MANCHESTER UNITED,SATURDAY AFTERNOON,Saturday afternoon is when Manchester United i...,5,18073,18081,1998,"[0.06369853019714355, 0.0025729986373335123, -..."
13491,SCOTT MCTOMINAY,PAUL POGBA,McTominay is currently performing the role tha...,8,18082,18083,1999,"[0.050501130521297455, 0.005157089792191982, -..."
13492,SCOTT MCTOMINAY,BRUNO FERNANDES,Scott McTominay's performance is noted alongsi...,6,18082,18084,1999,"[0.046916376799345016, 0.013256392441689968, -..."
13493,SCOTT MCTOMINAY,HARRY MAGUIRE,Scott McTominay's role is highlighted in conju...,6,18082,18085,1999,"[0.06499527394771576, 0.009948339313268661, -0..."
13494,UNITED,CHELSEA,United and Chelsea are rival football clubs co...,9,18087,18086,1999,"[0.011529958806931973, 0.0008717533200979233, ..."

In [6]:
import pandas as pd

# 通过entity_name进行分组，找出所有重名的实体
duplicated_entities = filtered_final_entities[filtered_final_entities.duplicated(subset='entity_name', keep=False)]

# 创建一个新的DataFrame用于存储新生成的关系
new_relationships = []

# 创建一个字典，方便通过entity_id查找entity_embedding
entity_embeddings = dict(zip(filtered_final_entities['entity_id'], filtered_final_entities['entity_embedding']))

# 创建一个字典，方便通过entity_id查找corpus_id
entity_corpus_ids = dict(zip(filtered_final_entities['entity_id'], filtered_final_entities['corpus_id']))

# 遍历每一个重名实体组，并创建新的关系
for entity_name, group in duplicated_entities.groupby('entity_name'):
    entity_ids = group['entity_id'].tolist()
    
    # 连接所有重名实体，生成新的关系
    for i in range(len(entity_ids)):
        for j in range(i + 1, len(entity_ids)):
            new_relationships.append({
                'source_entity': entity_name,
                'target_entity': entity_name,
                'relationship_description': 'SAME_NAME',
                'relationship_strength': 8,
                'source_entity_id': entity_ids[i],
                'target_entity_id': entity_ids[j],
                'corpus_id': entity_corpus_ids[entity_ids[i]],  # 使用source_entity对应的corpus_id
                'relationship_embedding': entity_embeddings[entity_ids[i]]  # 使用source_entity的embedding
            })

# 将新关系转换为DataFrame
new_relationships_df = pd.DataFrame(new_relationships)

# 将新生成的关系添加到原有的filtered_final_relationships中
filtered_final_relationships_with_duplicates = pd.concat([filtered_final_relationships, new_relationships_df], ignore_index=True)

# 输出结果
filtered_final_relationships_with_duplicates

,source_entity,target_entity,relationship_description,relationship_strength,source_entity_id,target_entity_id,corpus_id,relationship_embedding
0,AMAZON,CYBER MONDAY,Amazon is hosting numerous deals during Cyber ...,9,0,1,0,"[0.02443057671189308, -0.03799114748835564, -0..."
1,AMAZON,BLACK FRIDAY,Amazon began its Black Friday sale a week ahea...,8,0,2,0,"[0.054795797914266586, -0.031081540510058403, ..."
2,CYBER MONDAY,BLACK FRIDAY,"Cyber Monday follows Black Friday, with many d...",7,1,2,0,"[0.009650849737226963, -0.029358115047216415, ..."
3,"NOVEMBER 27, 2023",CYBER MONDAY,"November 27, 2023, is the date that marks the ...",10,3,1,0,"[0.007443748414516449, -0.01130700297653675, -..."
4,AMAZON,ECHO SHOW,"Amazon produces the Echo Show, integrating it ...",8,4,5,1,"[0.045543570071458817, -0.009272989816963673, ..."
...,...,...,...,...,...,...,...,...
74170,ZIM,ZIM,SAME_NAME,8,5542,5551,609,"[0.034851815551519394, -0.021064618602395058, ..."
74171,ZONE COVERAGE,ZONE COVERAGE,SAME_NAME,8,11185,11223,1229,"[0.01615450717508793, -0.002023662906140089, -..."
74172,ZOOM,ZOOM,SAME_NAME,8,3168,3539,345,"[-0.0039476389065384865, 0.010659453459084034,..."
74173,ZOSHA MILLMAN,ZOSHA MILLMAN,SAME_NAME,8,12454,13789,1374,"[0.03688004985451698, -0.018259698525071144, 0..."
74174,ZYLAN CHEATHAM,ZYLAN CHEATHAM,SAME_NAME,8,17925,17987,1980,"[0.03456365317106247, -0.008711005561053753, -..."

In [7]:
from src.gnn_clustering.data_loader import load_custom_data
from src.gnn_clustering.utils import get_device
from src.gnn_clustering.multihead_clustering import get_initial_leiden_results, get_multihead_leiden_results
from src.utils.utils import communities_to_labels
import numpy as np
import pandas as pd


# 设置设备
device = get_device()

# 数据加载
initial_data=load_custom_data(filtered_final_entities, filtered_final_relationships)
initial_data=initial_data.to(device)
data = load_custom_data(filtered_final_entities, filtered_final_relationships_with_duplicates)
data = data.to(device)

# 执行测试
initial_leiden_results  = get_initial_leiden_results(data=initial_data, device=device)
merge_leiden_results = get_initial_leiden_results(data=data, device=device)
multi_head_leiden_results = get_multihead_leiden_results(data=data, device=device)

# 将初始Leiden聚类结果添加到DataFrame
initial_communities_leiden = initial_leiden_results[0][0]
cluster_labels_initial = communities_to_labels(initial_communities_leiden, initial_data.num_nodes)
filtered_final_entities['initial_leiden_cluster'] = cluster_labels_initial

merge_communities_leiden = merge_leiden_results[0][0]
cluster_labels_merge = communities_to_labels(merge_communities_leiden, data.num_nodes)
filtered_final_entities['merge_leiden_cluster'] = cluster_labels_merge

# 将多头聚类结果添加到DataFrame
for head_index, clustering_result in enumerate(multi_head_leiden_results[0][0]):
    cluster_labels_multihead = communities_to_labels(clustering_result, data.num_nodes)
    filtered_final_entities[f'multihead_leiden_cluster_head_{head_index + 1}'] = cluster_labels_multihead

# 打印结果确认
filtered_final_entities

/home/bren901/coding/bren_venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

Epoch 1, Loss: 720222.3125
Epoch 20, Loss: 214726.6562
Epoch 40, Loss: 13562.6328
Epoch 60, Loss: 2197.2419
Epoch 80, Loss: 633.5264
Epoch 100, Loss: 416.6813
Epoch 120, Loss: 321.2896
Epoch 140, Loss: 265.6513
Epoch 160, Loss: 226.9164
Epoch 180, Loss: 198.9917
Epoch 200, Loss: 178.4417

/tmp/ipykernel_1646315/1078451509.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities['initial_leiden_cluster'] = cluster_labels_initial
/tmp/ipykernel_1646315/1078451509.py:30: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities['merge_leiden_cluster'] = cluster_labels_merge
/tmp/ipykernel_1646315/1078451509.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities[f'multihead_leiden_cluster_head_{head_index + 1}'] = cluster_labels_multihead
/tmp/ipykernel_1646315/1078451509.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities[f'multihead_leiden_cluster_head_{head_index + 1}'] = cluster_labels_multihead
/tmp/ipykernel_1646315/1078451509.py:35: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_final_entities[f'multihead_leiden_cluster_head_{head_index + 1}'] = cluster_labels_multihead

,entity_name,entity_type,description,entity_id,corpus_id,entity_embedding,initial_leiden_cluster,merge_leiden_cluster,multihead_leiden_cluster_head_1,multihead_leiden_cluster_head_2,multihead_leiden_cluster_head_3
0,AMAZON,ORGANIZATION,Amazon is a retail giant known for its extensi...,0,0,"[0.025474460795521736, -0.019272109493613243, ...",1494,14,57,32,25
1,CYBER MONDAY,EVENT,Cyber Monday is a significant shopping event t...,1,0,"[0.008677905425429344, -0.012837450951337814, ...",1494,20,57,32,25
2,BLACK FRIDAY,EVENT,Black Friday is a shopping holiday that takes ...,2,0,"[0.016857707872986794, -0.01078620832413435, -...",1494,20,57,32,25
3,"NOVEMBER 27, 2023",TIME,"November 27, 2023, is the date when Cyber Mond...",3,0,"[0.009768207557499409, -0.01335572637617588, -...",1494,19,57,32,25
4,AMAZON,ORGANIZATION,Amazon is a multinational technology company k...,4,1,"[0.029136504977941513, -0.007207231130450964, ...",360,14,57,32,25
...,...,...,...,...,...,...,...,...,...,...,...
18083,PAUL POGBA,PERSON,Paul Pogba is a former football player for Uni...,18083,1999,"[0.04045560583472252, -0.0013302824227139354, ...",1893,5,380,57,19
18084,BRUNO FERNANDES,PERSON,Bruno Fernandes is a football player with lead...,18084,1999,"[0.029299458488821983, 0.002235568594187498, -...",1893,5,380,38,19
18085,HARRY MAGUIRE,PERSON,Harry Maguire is a football player known for h...,18085,1999,"[0.0343484953045845, -0.007848457433283329, -0...",1893,5,50,38,19
18086,CHELSEA,ORGANIZATION,Chelsea is a football club that competes with ...,18086,1999,"[0.013079955242574215, -0.0021568776573985815,...",3254,0,50,6,19
18087,UNITED,ORGANIZATION,United is a football club that has players lik...,18087,1999,"[0.039028365164995193, 0.0027184761129319668, ...",3254,5,50,6,35

In [8]:
# 获取特定 entity_id 所在簇的节点数量
def get_cluster_node_count(df, entity_id, cluster_column):
    # 找到给定 entity_id 对应的簇标签
    cluster_label = df.loc[df['entity_id'] == entity_id, cluster_column].values[0]
    
    # 计算该簇中节点的数量
    cluster_node_count = df[df[cluster_column] == cluster_label].shape[0]
    
    return cluster_label, cluster_node_count

# 指定 entity_id
entity_id = 0  # 你要查找的 entity_id

# 聚类结果列名
cluster_columns = ['initial_leiden_cluster', 'merge_leiden_cluster'] + [col for col in filtered_final_entities.columns if col.startswith('multihead_leiden_cluster_head_')]

# 打印每个聚类所属簇的节点数量
for cluster_column in cluster_columns:
    cluster_label, node_count = get_cluster_node_count(filtered_final_entities, entity_id, cluster_column)
    print(f"Cluster label for {cluster_column} (entity_id {entity_id}): {cluster_label}")
    print(f"Number of nodes in the cluster: {node_count}\n")

Cluster label for initial_leiden_cluster (entity_id 0): 1494
Number of nodes in the cluster: 4

Cluster label for merge_leiden_cluster (entity_id 0): 14
Number of nodes in the cluster: 298

Cluster label for multihead_leiden_cluster_head_1 (entity_id 0): 57
Number of nodes in the cluster: 139

Cluster label for multihead_leiden_cluster_head_2 (entity_id 0): 32
Number of nodes in the cluster: 198

Cluster label for multihead_leiden_cluster_head_3 (entity_id 0): 25
Number of nodes in the cluster: 224

In [10]:
from collections import deque
from src.gnn_clustering.utils import get_all_related_relationships_within_cluster

# 示例调用
entity_id = 0  # 你要查找的 entity_id
cluster_column = 'multihead_leiden_cluster_head_1'  # 聚类结果列
related_relationships = get_all_related_relationships_within_cluster(filtered_final_entities, filtered_final_relationships_with_duplicates, entity_id, cluster_column)

# 打印属于该 entity_id 的所有相关关系数量
print(len(related_relationships))
# 打印具体的关系
related_relationships

20

,source_entity,target_entity,relationship_description,relationship_strength,source_entity_id,target_entity_id,corpus_id,relationship_embedding
0,AMAZON,CYBER MONDAY,Amazon is hosting numerous deals during Cyber ...,9,0,1,0,"[0.02443057671189308, -0.03799114748835564, -0..."
1,AMAZON,BLACK FRIDAY,Amazon began its Black Friday sale a week ahea...,8,0,2,0,"[0.054795797914266586, -0.031081540510058403, ..."
2,CYBER MONDAY,BLACK FRIDAY,"Cyber Monday follows Black Friday, with many d...",7,1,2,0,"[0.009650849737226963, -0.029358115047216415, ..."
3,"NOVEMBER 27, 2023",CYBER MONDAY,"November 27, 2023, is the date that marks the ...",10,3,1,0,"[0.007443748414516449, -0.01130700297653675, -..."
4,AMAZON,ECHO SHOW,"Amazon produces the Echo Show, integrating it ...",8,4,5,1,"[0.045543570071458817, -0.009272989816963673, ..."
5,AMAZON,FIRE TV,"Amazon develops and sells the Fire TV, a produ...",8,4,7,1,"[0.021016299724578857, -0.025722812861204147, ..."
6,AMAZON,KINDLE,"Amazon designs and markets the Kindle, a popul...",8,4,8,1,"[0.012262783013284206, -0.0032894627656787634,..."
10,ECHO SHOW,ALEXA,The Echo Show utilizes Alexa to execute voice ...,9,5,6,1,"[0.0503154918551445, 0.017121654003858566, -0...."
11,FIRE TV,AMAZON,"Fire TV is a product created by Amazon, provid...",8,7,4,1,"[0.01219999324530363, -0.023149143904447556, -..."
12,KINDLE,AMAZON,Kindle is an Amazon product that revolutionize...,8,8,4,1,"[0.020139290019869804, 0.0026215692050755024, ..."
73,AMAZON,SELLERS,Amazon provides a platform for sellers to list...,8,91,93,11,"[0.032026004046201706, -0.030965404585003853, ..."
74,SELLERS,CUSTOMERS,Sellers provide products to customers through ...,8,93,94,11,"[0.021552415564656258, -0.015566838905215263, ..."
75,FTC,AMAZON,"The FTC filed a complaint against Amazon, indi...",7,92,91,11,"[0.019976206123828888, -0.023729953914880753, ..."
76,FTC,SELLERS,The FTC's actions regarding Amazon may affect ...,6,92,93,11,"[0.04527241364121437, -0.03313612565398216, -0..."
77,SCOTT NEEDHAM,AMAZON,Scott Needham has been critical of Amazon's pr...,7,95,96,12,"[0.0386405885219574, -0.024442624300718307, -0..."
78,SCOTT MOLLER,AMAZON,Scott Moller is an Amazon seller who benefits ...,8,98,96,12,"[0.013038179837167263, -0.018628861755132675, ..."
79,FULFILLMENT BY AMAZON,AMAZON,Fulfillment by Amazon is a service provided by...,9,97,96,12,"[0.03618916869163513, -0.014793498441576958, -..."
80,SCOTT NEEDHAM,FULFILLMENT BY AMAZON,Scott Needham discusses the value and perceive...,6,95,97,12,"[0.054290372878313065, -0.0034626733977347612,..."
81,SCOTT MOLLER,FULFILLMENT BY AMAZON,Scott Moller highlights the benefits of using ...,7,98,97,12,"[0.046069514006376266, -0.0031631614547222853,..."
82,MOLLER,AMAZON,Moller utilizes Amazon's platform to sell gril...,9,99,101,13,"[0.016477515920996666, -0.021527880802750587, ..."

In [15]:
# from src.utils.message_templates import generate_community_report_template

def generate_community_report_template(core_entity_id, df_entities, related_relationships):
    """
    Generates a community report message based on the given parameters.
    
    Parameters:
    core_entity_id (int): The ID of the core entity.
    df_entities (DataFrame): DataFrame containing all entities.
    related_relationships (DataFrame): DataFrame containing relationships related to the core entity.
    
    Returns:
    str: A message formatted for generating a community report.
    """
    # Extract core entity information
    core_entity = df_entities[df_entities['entity_id'] == core_entity_id].iloc[0]
    core_entity_text = f"Core_Entity\n\nid,entity,description\n{core_entity['entity_id']},{core_entity['entity_name']},{core_entity['description']}\n"
    
    # Extract related entities information
    related_entity_ids = set(related_relationships['source_entity_id']).union(set(related_relationships['target_entity_id']))
    related_entity_ids.discard(core_entity_id)
    related_entities = df_entities[df_entities['entity_id'].isin(related_entity_ids)]
    related_entities_text = "Related_Entities\n\nid,entity,description\n" + "\n".join(
        f"{row['entity_id']},{row['entity_name']},{row['description']}" for _, row in related_entities.iterrows()
    )
    
    # Extract relationships information
    relationships_text = "Relationships\n\nid,source,target,description\n" + "\n".join(
        f"{idx},{row['source_entity']},{row['target_entity']},{row['relationship_description']}"
        for idx, row in related_relationships.iterrows()
    )
    
    # Combine all parts to form input_text
    input_text = f"{core_entity_text}\n{related_entities_text}\n\n{relationships_text}"
    
    return f"""
    You are a community analyst.

    # Goal
    Write a comprehensive assessment report of a community as a community analyst. The content of this report includes an overview of the community's key entities and relationships.

    # Report Structure
    The report should include the following sections:
    - TITLE: community's name that represents its key entities - title should be short but specific. When possible, include representative named entities in the title.
    - SUMMARY: An executive summary of the community's overall structure, how its entities are related to each other, and significant points associated with its entities.
    - DETAILED FINDINGS: A list of 5-10 key insights about the community. Each insight should have a short summary followed by multiple paragraphs of explanatory text grounded according to the grounding rules below. Be comprehensive.

    Return output as a well-formed JSON-formatted string with the following format. Don't use any unnecessary escape sequences. The output should be a single JSON object that can be parsed by json.loads.
        {{
            "title": "<report_title>",
            "summary": "<executive_summary>",
            "findings": [{{"summary":"<insight_1_summary>", "explanation": "<insight_1_explanation>"}}, {{"summary":"<insight_2_summary>", "explanation": "<insight_2_explanation>"}}]
        }}

    # Grounding Rules
    After each paragraph, add data record reference if the content of the paragraph was derived from one or more data records. Reference is in the format of [records: <record_source> (<record_id_list>, ...<record_source> (<record_id_list>)]. If there are more than 10 data records, show the top 10 most relevant records.
    Each paragraph should contain multiple sentences of explanation and concrete examples with specific named entities. All paragraphs must have these references at the start and end. Use "NONE" if there are no related roles or records. Everything should be in English.

    Example paragraph with references added:
    This is a paragraph of the output text [records: Entities (1, 2, 3), Claims (2, 5), Relationships (10, 12)]

    # Example Input
    -----------
    Text:

    Entities

    id,entity,description
    5,ABILA CITY PARK,Abila City Park is the location of the POK rally

    Related_Entities

    id,entity,description
    6,POK,POK is an organization holding a rally in Abila City Park
    7,CENTRAL BULLETIN,Central Bulletin is a media outlet covering the POK rally

    Relationships

    id,source,target,description
    37,ABILA CITY PARK,POK RALLY,Abila City Park is the location of the POK rally
    38,ABILA CITY PARK,POK,POK is holding a rally in Abila City Park
    39,ABILA CITY PARK,POKRALLY,The POKRally is taking place at Abila City Park
    40,ABILA CITY PARK,CENTRAL BULLETIN,Central Bulletin is reporting on the POK rally taking place in Abila City Park

    Output:
    {{
        "title": "Abila City Park and POK Rally",
        "summary": "The community revolves around the Abila City Park, which is the location of the POK rally. The park has relationships with POK, POKRALLY, and Central Bulletin, all of which are associated with the rally event.",
        "findings": [
            {{
                "summary": "Abila City Park as the central location",
                "explanation": "Abila City Park is the central entity in this community, serving as the location for the POK rally. This park is the common link between all other entities, suggesting its significance in the community. The park's association with the rally could potentially lead to issues such as public disorder or conflict, depending on the nature of the rally and the reactions it provokes. [records: Entities (id: 5), Relationships (id: 37, 38, 39, 40)]"
            }},
            {{
                "summary": "POK's role in the community",
                "explanation": "POK is another key entity in this community, being the organizer of the rally at Abila City Park. The nature of POK and its rally could be a potential source of threat, depending on their objectives and the reactions they provoke. The relationship between POK and the park is crucial in understanding the dynamics of this community. [records: Relationships (id: 38)]"
            }},
            {{
                "summary": "POKRALLY as a significant event",
                "explanation": "The POKRALLY is a significant event taking place at Abila City Park. This event is a key factor in the community's dynamics and could be a potential source of threat, depending on the nature of the rally and the reactions it provokes. The relationship between the rally and the park is crucial in understanding the dynamics of this community. [records: Relationships (id: 39)]"
            }},
            {{
                "summary": "Role of Central Bulletin",
                "explanation": "Central Bulletin is reporting on the POK rally taking place in Abila City Park. This suggests that the event has attracted media attention, which could amplify its impact on the community. The role of Central Bulletin could be significant in shaping public perception of the event and the entities involved. [records: Relationships (id: 40)]"
            }}
        ]
    }}

    # Real Data

    Use the following text for your answer. Do not make anything up in your answer.

    {input_text}

    Output:"""


message=generate_community_report_template(entity_id,filtered_final_entities[['entity_name', 'entity_type', 'description', 'entity_id', 'corpus_id']],related_relationships)
message
# Save the message to a text file
with open('community_report.txt', 'w') as file:
    file.write(message)